name: newtok_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  dio: ^5.5.0+1
  fluttertoast: ^8.2.6
  cloud_firestore: ^5.2.1
  firebase_database: ^11.0.4
  file_picker: ^8.0.7
  csv: ^6.0.0
  cached_network_image: ^3.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env