// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGHlCwacSX7a14POBtH9FZKxzreq4ckQ',
    appId: '1:286716395424:android:909a9b0b16db2bc35faec5',
    messagingSenderId: '286716395424',
    projectId: 'newtok-app',
    storageBucket: 'newtok-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQ_3uRo7xWK3KmAUdjzBqofRhAndOXWs',
    appId: '1:286716395424:ios:236153596bed8c425faec5',
    messagingSenderId: '286716395424',
    projectId: 'newtok-app',
    storageBucket: 'newtok-app.appspot.com',
    iosBundleId: 'com.example.newtokTest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43YZiydnZvHwfwWfhjkxxVrfHOmN83ng',
    appId: '1:286716395424:web:062c203b268fa8a65faec5',
    messagingSenderId: '286716395424',
    projectId: 'newtok-app',
    authDomain: 'newtok-app.firebaseapp.com',
    storageBucket: 'newtok-app.appspot.com',
    measurementId: 'G-W1YG27F43G',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQ_3uRo7xWK3KmAUdjzBqofRhAndOXWs',
    appId: '1:286716395424:ios:236153596bed8c425faec5',
    messagingSenderId: '286716395424',
    projectId: 'newtok-app',
    storageBucket: 'newtok-app.appspot.com',
    iosBundleId: 'com.example.newtokTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD43YZiydnZvHwfwWfhjkxxVrfHOmN83ng',
    appId: '1:286716395424:web:a5fa7f349354c3b45faec5',
    messagingSenderId: '286716395424',
    projectId: 'newtok-app',
    authDomain: 'newtok-app.firebaseapp.com',
    storageBucket: 'newtok-app.appspot.com',
    measurementId: 'G-CBV9PZJQ5E',
  );

}